

development:
  sessions:
    default:
      database: siji
      hosts:
      - localhost:27017

production:
  sessions:
    default:
      uri: <&= ENV['MONGOLAB_URI'] &>
      options:
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 30
        safe: true
        refresh_interval: 10