

development:
  sessions:
    default:
      database: siji
      hosts:
      - localhost:27017

production:
  sessions:
    default:
      uri: <&= ENV['MONGOLAB_URI'] &>
      database: siji
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        timeout: 30