

development:
  clients:
    default:
      database: siji
      hosts:
      - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
        connect_timeout: 15
