

development:
  sessions:
    default:
      database: siji
      hosts:
      - localhost:27017

production:
  sessions:
    default:
      database: siji
      hosts:
      - <&= ENV['MONGOLAB_HOST'] &>
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0